- platform: mqtt
  name: "outhouse_reflector"
  state_topic: "stat/sonoff1/POWER"
  command_topic: "cmnd/sonoff1/POWER"
  qos: 1
  icon: mdi:lightbulb
#  payload_on: "ON"
#  payload_off: "OFF"
  retain: true
