- platform: mqtt
  name: "seasone_light"
  state_topic: "stat/sonoff2/POWER"
  command_topic: "cmnd/sonoff2/POWER"
  qos: 1
  icon: mdi:lightbulb
#  payload_on: "ON"
#  payload_off: "OFF"
  retain: true
