- i2c_address: 0x24
  int_pin: 22
  inputs:
    1:
      name: kitchen_button
      type: button
    2:
      name: kitchen_button1
      type: button
    3:
      name: kitchen_button2
      type: button
    4:
      name: kitchen_button3
      type: button
    5:
      name: kitchen_leak
      type: moisture
    6:
      name: entrance_pir
      type: motion
    7:
      name: entrance_ring
      type: button
      actions: [down, up, single]
    8:
      name: gate_ring
      type: button
      actions: [down, up, single]
  outputs:
    1:
      name: kitchen_light2
      type: light
    2:
      name: kitchen_light3
      type: light
    3:
      name: livingroom_light3
      type: light
    4:
      name: REL36
      type: switch
    5:
      name: REL37
      type: switch
    6:
      name: REL38
      type: switch
    7:
      name: REL39
      type: switch
    8:
      name: hall_doorbell
      type: switch
