#--------------------------------------------------------------------------------
# při události click nebo hold a zapnutém světle se světlo vypne
#--------------------------------------------------------------------------------
- alias: outhouse_light_off
  initial_state: on
  trigger:
    - platform: event
      event_type: ioboard_event
      event_data:
        click_action: single
        entity_id: binary_sensor.outhouse_button
    - platform: event
      event_type: ioboard_event
      event_data:
        click_action: hold
        entity_id: binary_sensor.outhouse_button
  condition:
    - condition: state
      entity_id: light.outhouse_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.outhouse_light
    - service: input_select.select_option
      data:
        entity_id: input_select.outhouse_light_source
        option: none

#--------------------------------------------------------------------------------
# při události click nebo hold a vypnutém světle se světlo zapne
#--------------------------------------------------------------------------------
- alias: outhouse_light_on
  initial_state: on
  trigger:
    - platform: event
      event_type: ioboard_event
      event_data:
        click_action: single
        entity_id: binary_sensor.outhouse_button
    - platform: event
      event_type: ioboard_event
      event_data:
        click_action: hold
        entity_id: binary_sensor.outhouse_button
  condition:
    - condition: state
      entity_id: light.outhouse_light
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.outhouse_light
    - service: input_select.select_option
      data_template:
        option: "{{ trigger.event.data['click_action'] }}"
        entity_id: input_select.outhouse_light_source

#--------------------------------------------------------------------------------
# po události click se světlo za 5 minuty vypne
#--------------------------------------------------------------------------------
- alias: outhouse_light_click_off
  initial_state: on
  trigger:
    platform: state
    entity_id: input_select.wc_light_source
    to: single
    for:
      minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.outhouse_light
    - service: input_select.select_option
      data:
        entity_id: input_select.outhouse_light_source
        option: none

#--------------------------------------------------------------------------------
# po události hold se světlo za 15 minuty vypne
#--------------------------------------------------------------------------------
- alias: outhouse_light_hold_off
  initial_state: on
  trigger:
    platform: state
    entity_id: input_select.outhouse_light_source
    to: hold
    for:
      minutes: 15
  action:
    - service: light.turn_off
      entity_id: light.outhouse_light
    - service: input_select.select_option
      data:
        entity_id: input_select.outhouse_light_source
        option: none


#--------------------------------------------------------------------------------
#          POHYBOVÉ ČIDLO
#--------------------------------------------------------------------------------
# při pohybu a vypnutých světlech se rosvítí 
#--------------------------------------------------------------------------------
- alias: outhouse_light_motion_on
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.outhouse_pir
    to: 'on'
  condition:
    - condition: state
      entity_id: light.outhouse_light
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.outhouse_light
    - service: input_select.select_option
      data:
        entity_id: input_select.outhouse_light_source
        option: motion

#--------------------------------------------------------------------------------
# pokud bylo rosvíceno pohybem tak se po 2 minutách vypne světlo
#--------------------------------------------------------------------------------
- alias: outhouse_light_motion_off
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.outhouse_pir
    to: 'off'
    for:
      minutes: 2
  condition:
    - condition: state
      entity_id: input_select.outhouse_light_source
      state: motion
  action:
    - service: light.turn_off
      entity_id: light.outhouse_light
    - service: input_select.select_option
      data:
        entity_id: input_select.outhouse_light_source
        option: none
