#--------------------------------------------------------------------------------
# vypnutí automatizovaných prvků při spuštění home assistant
#--------------------------------------------------------------------------------
- alias: water_open_close_home_assistant_start
  initial_state: on
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: switch.turn_off
      entity_id: switch.utility_water_open
    - service: switch.turn_off
      entity_id: switch.utility_water_close

#####################################################
#  Automatické vypnutí uzávěru vody po jeho aktivaci
#####################################################
- alias: water_close_auto_off
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.utility_water_close
    to: 'on'
    for:
      seconds: 10
  action:
    - service: switch.turn_off
      entity_id: switch.utility_water_close

- alias: water_open_auto_off
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.utility_water_open
    to: 'on'
    for:
      seconds: 10
  action:
    - service: switch.turn_off
      entity_id: switch.utility_water_open
