#--------------------------------------------------------------------------------
# při události click nebo hold a zapnutém světle se světlo vypne
#--------------------------------------------------------------------------------
- alias: wc_light_off
  initial_state: on
  trigger:
    - platform: event
      event_type: ioboard_event
      event_data:
        click_action: single
        entity_id: binary_sensor.wc_button
    - platform: event
      event_type: ioboard_event
      event_data:
        click_action: hold
        entity_id: binary_sensor.wc_button
  condition:
    - condition: state
      entity_id: light.wc_light
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.wc_light
    - service: input_select.select_option
      data:
        entity_id: input_select.wc_light_source
        option: none

#--------------------------------------------------------------------------------
# při události click nebo hold a vypnutém světle se světlo zapne
#--------------------------------------------------------------------------------
- alias: wc_light_on
  initial_state: on
  trigger:
    - platform: event
      event_type: ioboard_event
      event_data:
        click_action: single
        entity_id: binary_sensor.wc_button
    - platform: event
      event_type: ioboard_event
      event_data:
        click_action: hold
        entity_id: binary_sensor.wc_button
  condition:
    - condition: state
      entity_id: light.wc_light
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.wc_light
    - service: input_select.select_option
      data_template:
        option: "{{ trigger.event.data['click_action'] }}"
        entity_id: input_select.wc_light_source
    - service: fan.turn_on
      data_template:
        entity_id: >
          {% if trigger.event.data["click_action"] == "hold" %}
            fan.wc_fan
          {% else %}
            fan.wc_fan_dummy
          {% endif %}

#--------------------------------------------------------------------------------
# po události click se světlo za 2 minuty vypne
#--------------------------------------------------------------------------------
- alias: wc_light_click_off
  initial_state: on
  trigger:
    platform: state
    entity_id: input_select.wc_light_source
    to: single
    for:
      minutes: 2
  action:
    - service: light.turn_off
      entity_id: light.wc_light
    - service: input_select.select_option
      data:
        entity_id: input_select.wc_light_source
        option: none

#--------------------------------------------------------------------------------
# po události hold se světlo za 5 minuty vypne
#--------------------------------------------------------------------------------
- alias: wc_light_hold_off
  initial_state: on
  trigger:
    platform: state
    entity_id: input_select.wc_light_source
    to: hold
    for:
      minutes: 5
  action:
    - service: light.turn_off
      entity_id: light.wc_light
    - service: input_select.select_option
      data:
        entity_id: input_select.wc_light_source
        option: none


#--------------------------------------------------------------------------------
#          POHYBOVÉ ČIDLO
#--------------------------------------------------------------------------------
# při pohybu a vypnutých světlech se rosvítí 
#--------------------------------------------------------------------------------
- alias: wc_light_motion_on
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.wc_pir
    to: 'on'
  condition:
    - condition: state
      entity_id: light.wc_light
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.wc_light
    - service: input_select.select_option
      data:
        entity_id: input_select.wc_light_source
        option: motion

#--------------------------------------------------------------------------------
# pokud bylo rosvíceno pohybem tak se po 2 minutách vypne světlo
#--------------------------------------------------------------------------------
- alias: wc_light_motion_off
  initial_state: on
  trigger:
    platform: state
    entity_id: binary_sensor.wc_pir
    to: 'off'
    for:
      minutes: 2
  condition:
    - condition: state
      entity_id: input_select.wc_light_source
      state: motion
  action:
    - service: light.turn_off
      entity_id: light.wc_light
    - service: input_select.select_option
      data:
        entity_id: input_select.wc_light_source
        option: none


#--------------------------------------------------------------------------------
#            VENTILÁTOR
#--------------------------------------------------------------------------------
# po zapnutí světel pohybem se zapne ventilátor za minutu
#--------------------------------------------------------------------------------
- alias: wc_fan_on
  initial_state: on
  trigger:
    platform: state
    entity_id: light.wc_light
    to: 'on'
    for:
      minutes: 2
  condition:
    - condition: state
      entity_id: fan.wc_fan
      state: 'off'
  action:
    - service: fan.turn_on
      entity_id: fan.wc_fan

#--------------------------------------------------------------------------------
# po vypnutí světel se vypne ventilátor pokud běžel za minutu
#--------------------------------------------------------------------------------
- alias: wc_fan_off
  initial_state: on
  trigger:
    platform: state
    entity_id: light.wc_light
    to: 'off'
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: fan.wc_fan
      state: 'on'
  action:
    - service: fan.turn_off
      entity_id: fan.wc_fan
