- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: disk_free
      arg: /home
    - type: memory_free
    - type: memory_use_percent
    - type: load_15m
    - type: network_in
      arg: eth0
    - type: network_out
      arg: eth0
    - type: ipv4_address
      arg: eth0
    - type: last_boot
    - type: since_last_boot

#    - type: processor_use
#    - type: disk_use
#      arg: /home
#    - type: memory_use
#    - type: packets_in
#      arg: eth0
#    - type: packets_out
#      arg: eth0
