linux_server_card:
  name: Hass Server
  entities:
     - sensor.load_15m
     - sensor.disk_free_home
     - sensor.disk_use_percent_home
     - sensor.memory_free
     - sensor.memory_use_percent
     - sensor.network_in_eth0
     - sensor.network_out_eth0
     - sensor.ipv4_address_eth0
     - sensor.last_boot
     - sensor.since_last_boot
