utility_room:
  name: Technická místnost
  control: hidden
  entities:
    - input_select.utility_light_source
    - binary_sensor.utility_button
    - binary_sensor.utility_c_off
    - binary_sensor.utility_hdo
    - binary_sensor.utility_leak
    - binary_sensor.utility_power
    - binary_sensor.utility_watermeter
    - light.utility_light
    - switch.utility_c_off
    - switch.utility_water_close
    - switch.utility_water_open
